tasks:
    images:
        build:
            services:
                web:
                    steps:
                        - docker_file_path: ./Dockerfile-build
                          image: ${IMAGE_NAME_BUILD}
                          write_artifacts:
                            - name: dist
                              path: /dist
                        - docker_file_path: ./Dockerfile
                          image: ${IMAGE_NAME}
                          read_artifacts:
                            - name: dist
                              path: /dist

    wait_product_owner:
         manual_approval: ~

    deployment:
        deploy:
            cluster: ${CLUSTER}
            services:
                web:
                    specification:
                        accessibility:
                            from_external: true

    integration:
        web_hook:
            url: ${WEBHOOK_URL}

pipelines:
    - name: Production
      condition: 'code_reference.branch in ["master"]'
      tasks: [ images, deployment ]