tasks:
    images:
        build:
            services:
                web:
                    steps:
                        - docker_file_path: ./docker/Buildfile
                          write_artifacts:
                              - name: built-files-artifact
                                path: /app/built-files
                        - docker_file_path: ./docker/Dockerfile
                          image: ${IMAGE_NAME}
                          read_artifacts:
                              - name: built-files-artifact
                                path: /built-files

    wait_product_owner:
         manual_approval: ~

    deployment:
        deploy:
            cluster: ${CLUSTER}
            services:
                web:
                    specification:
                        accessibility:
                            from_external: true

    integration:
        web_hook:
            url: ${WEBHOOK_URL}

pipelines:
    - name: Production
      condition: 'code_reference.branch in ["master"]'
      tasks: [ images, deployment ]